site_name: ${{ values.friendly_name }} Docs
repo_url: https://github.com/${{ values.github_organization }}/${{ values.project_slug }}
theme: readthedocs

nav:
  - Home: index.md
  - Architecture: architecture.md