apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: java-springboot-template
  title: Java Spring Boot Service
  description: Scaffold a new Java Spring Boot service with Devbox, TechDocs, CI, and Backstage integration.
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service Information
      required:
        - friendly_name
      properties:
        friendly_name:
          type: string
          title: Service Name
          description: Friendly name of the new service that will be used for display purposes
          default: My Spring Boot Service
        project_slug:
          type: string
          title: Project Slug
          description: Slugified name for repository (optional, defaults from friendly_name)
        description:
          type: string
          title: Description
          default: A Java service scaffolded with Backstage
        java_version:
          type: string
          title: Java Version
          enum: ["17", "21"]
          enumNames: [Java 17, Java 21]
          default: "17"
        maven_version:
          type: string
          default: "3.9.6"
        spring_boot_version:
          type: string
          default: "3.2.0"
        github_organization:
          type: string
          title: GitHub Organization
          default: dean-chin-altimetrik

  steps:
    - id: fetch-base
      name: Fetch base template
      action: fetch:template
      input:
        url: https://github.com/dean-chin-altimetrik/platform-backstage-templates/blob/main/service-templates/java-springboot-template/skeleton
        values:
          friendly_name: "${{ parameters.friendly_name }}"
          project_slug: "${{ parameters.project_slug | default(parameters.friendly_name | lower | replace(' ', '-')) }}"
          description: "${{ parameters.description }}"
          group_id: "com.altimetrik"
          java_version: "${{ parameters.java_version }}"
          maven_version: "${{ parameters.maven_version }}"
          spring_boot_version: "${{ parameters.spring_boot_version }}"
          java_package_dir: "${{ 'com.altimetrik' | replace('.', '/') }}"
          java_package_name: "${{ 'com.altimetrik' | replace('-', '_') }}"

    - id: publish
      name: Publishing to a GitHub repository
      action: publish:github
      input:
        repoUrl: github.com?repo=${{parameters.project_slug}}&owner=${{parameters.github_organization}}
        defaultBranch: main
        description: "${{ parameters.description }}"
        repoVisibility: public

    - id: register
      name: Register in Backstage catalog
      action: catalog:register
      input:
        catalogInfoUrl: "https://raw.githubusercontent.com/${{ parameters.github_organization }}/${{ parameters.project_slug }}/refs/head/main/catalog-info.yaml"
