apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: java-springboot-templae
  title: Java Spring Boot Service
  description: Scaffold a new Java Spring Boot service with Devbox, TechDocs, CI, and Backstage integration.
spec:
  owner: platform-team
  type: service
  parameters:
    - title: Service Information
      required:
        - friendly_name
      properties:
        friendly_name:
          type: string
          title: Service Name
          description: Friendly name of the new service that will be used for display purposes
          default: My Spring Boot Service
        project_slug:
          type: string
          title: Project Slug        
        description:
          type: string
          title: Description
          default: A Java service scaffolded with Backstage
        java_version:
          type: string
          title: Java version
          enum:
            - "17"
            - "21"
          enumNames:
            - Java 17
            - Java 21
          default: "17"
        maven_version:
          type: string
          default: "3.9.6"
        spring_boot_version:
          type: string
          default: "3.2.0"
        github_organization:
          type: string
          title: GitHub Organization
          default: dean-chin-altimetrik

  steps:
    - id: fetch-base
      name: Fetch base template
      action: fetch:template
      input:
        url: github:dean-chin-altimetrik/platform-backstage-templates/blob/main/service-templates/java-springboot-template
        targetPath: ./output
        values:
          friendly_name: "{{ parameters.friendly_name }}"
          project_slug: "{{ parameters.friendly_name | lower | replace(' ', '-') }}"
          description: "{{ parameters.description }}"
          group_id: "com.altimetrik"
          java_version: "{{ parameters.java_version }}"
          maven_version: "{{ parameters.maven_version }}"
          spring_boot_version: "{{ parameters.spring_boot_version }}"
          java_package_dir: "{{ parameters.group_id | replace('.', '/') }}"
          java_package_name: "{{ parameters.group_id | replace('-', '_') }}"

    - id: register
      name: Register in Backstage catalog
      action: catalog:register
      input:
        # repoContentsUrl: "{{ output.repoContentsUrl }}"
        catalogInfoPath: "/catalog-info.yaml"